In [2]:
import pyecharts
pyecharts.__version__

'0.5.8'

In [3]:
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import scale, minmax_scale,robust_scale
os.getcwd()

'/home/pirl/포항공대 /아카데미수업내용/4주차'

In [4]:
df = pd.read_csv(os.getcwd()+'/3. Big Data 분석_실습화일/titanic.csv')
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.758889,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,13.002570,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,30.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
survived = df[df['Survived']==1]['Sex'].value_counts()
dead = df[df['Survived']==0]['Sex'].value_counts()
df_sex = pd.DataFrame([survived,dead])
df_sex.index = ['Survived','Dead']
df_sex.plot(kind='bar',stacked=True, figsize=(10,5))

In [179]:
q=pd.read_csv('b.csv')
w=pd.read_csv('d.csv')


line = pyecharts.Line('')
line.add("죽음", q['ran_Age'], q['0'],is_label_show=True, is_smooth=True ,symbol=None)
line.add("생존", w['ran_Age'], w['0'],is_label_show=True, is_smooth=True ,symbol=None)
line.height = 500
line.width = 800
line